version: '3'

services:
    ui:
        image: sogloarcadius/portfolio-frontend:httponly
        build: 
            context: .
            dockerfile: ./Dockerfile.httponly
            args:
                BIOGRAPHY_API_URL: ${BIOGRAPHY_API_URL}
                PROJECTS_API_URL: ${PROJECTS_API_URL}
        ports:
            - "80:80"