version: '3'

services:
    syslog-ng:
        image: balabit/syslog-ng
        command: "--no-caps"
        volumes :
            - ./confs/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
            - /var/log:/var/log/
    frontend:
        image: sogloarcadius/portfolio-frontend:https
        build: 
            context: .
            dockerfile: ./Dockerfile.https
            args:
                BIOGRAPHY_API_URL: ${BIOGRAPHY_API_URL}
                PROJECTS_API_URL: ${PROJECTS_API_URL}
                SYSLOG_HOST: ${SYSLOG_HOST}
                SYSLOG_PORT: ${SYSLOG_PORT}
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /docker/portfolio/volumes/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
            - /docker/portfolio/volumes/etc/letsencrypt/live/sogloarcadius.com/fullchain.pem:/etc/letsencrypt/live/sogloarcadius.com/fullchain.pem
            - /docker/portfolio/volumes/etc/letsencrypt/live/sogloarcadius.com/privkey.pem:/etc/letsencrypt/live/sogloarcadius.com/privkey.pem
        depends_on:
            - syslog-ng